export const FIELD_IDS = {
  ACCEPT_POLICIES: "accept_policies",
  CONFIRM_PASSWORD: "confirm_password",
  COUNTRY: "country",
  COUNTRY_CODE: "country_code",
  CURRENT_PASSWORD: "current_password",
  EMAIL: "email",
  LAST_NAME: "last_name",
  MESSAGE: "message",
  NAME: "name",
  NEW_PASSWORD: "new_password",
  NO_ROBOT: "no_robot",
  PASSWORD: "password",
  PHONE: "phone",
  USERNAME: "username",
} as const;
