export const ARIA_LABEL = {
  TOGGLE_BILLING: "Toggle annual billing",
  LOADING_PLANS_TABLE: "Loading plans comparison table",
  PLANS_COMPARISON_LOADING: "Plans comparison loading",
  WHATSAPP: "Chat on WhatsApp",
  SUBMITING_FORM: "Submitting form",
  SEND_MESSAGE: "Send message",
  CONTACT_FORM: "Contact form",
  CLOSE_MODAL: "Close modal",
  CLOSE_TOAST: "Close toast",
  ORIGINAL_PRICE: "Original price",
  DISCOUNTED_PRICE: "Discounted price",
  PRICE_WITHOUT_DISCOUNT: "Price without discount",
  DISCOUNT_APPLIED: "Discount applied",
  NO_DISCOUNT: "No discount",
  SELECT_PLAN: "Select plan",
  SAVINGS: "Savings",
  PLAN_OPTIONS: "Plan options",
  PLAN_HEADER: "Plan header",
  PLAN_ARTICLE: "Plan",
  PLAN_PRICE: "Plan price",
  PLAN_FINAL_PRICE: "Final price",
  PLAN_OLD_PRICE: "Original price",
  PLAN_DISCOUNT: "Discount applied",
  PLAN_FOOTER: "Plan footer",
  PLAN_MONTHLY_PRICE: "Monthly price",
  PLAN_CONTRACT: "Plan contract",
  TOGGLE_PASSWORD_VISIBILITY: "Mostrar/ocultar contraseña",
};
