export const PATHS = {
  ACCESS: {
    FIRST_LOGIN: "/acceso/primer-ingreso",
    LOGIN: "/acceso/ingreso",
    PASSWORD_CHANGE: "/acceso/cambio-contrasena",
    PASSWORD_RECOVERY: "/acceso/recuperar-contrasena",
    WORK_MODE: "/acceso/modo-de-trabajo",
  },
  ADMIN: {
    CATEGORIES: "/administracion/categorias",
    COMBOS: "/administracion/combos",
    EXTRAS: "/administracion/extras",
    RATES: "/administracion/tarifas",
    REPORTS: "/administracion/reportes",
    ROOT: "/administracion",
    UNITS: "/administracion/unidades",
    WORKERS: "/administracion/trabajadores",
  },
  COMMON: {
    CATEGORY: "/tablero/categoria",
    DASHBOARD: "/tablero",
    HISTORY: "/historial",
    PROFILE: "/perfil",
    ROOT: "/",
  },
  OPERATIONS: {
    CLOSE: "/operaciones/cierre",
    DISPATCH: "/operaciones/despacho",
    INVENTORY: "/operaciones/inventario",
    MACHINES: "/operaciones/maquinas",
    MAINTENANCE: "/operaciones/mantenimiento",
    ROOT: "/operaciones",
  },
  RESERVATIONS: {
    CALENDAR: "/reservas/calendario",
    DETAIL: "/reservas/detalle",
    NEW: "/reservas/nueva",
    ROOT: "/reservas",
  },
} as const;
