export const STRING = {
  Empty: "",
  ZERO: "0",
  SPACE: " ",
  COUNTRY_CODE: "+506",
  SEMICOLON: ";",
  COMMA: ",",
  COLON: ":",
  NO: "no",
  CLASSNAME: "className",
  ALT: "alt",
  LEFT: "left",
  RIGHT: "right",
  ASTERISK: "*",
  N_A: "N/A",
  ERROR: "Error",
  TRUE: "true",
  FALSE: "false",
  BOOLEAN: "boolean",
  SPINNER: "spinner",
  FORM: "form",
  HASH: "#",
  DASH: "-",
  CONTENT: "content",
  OBJECT: "object",
  MESSAGE: "message",
  STRING: "string",
  SUCCESSFUL: "successful",
  NON_BREAKING_SPACE: "\u00A0",
  FIRST: "«",
  PREVIOUS: "‹",
  NEXT: "›",
  LAST: "»",
  THREE_DOTS: "…",
  COMMA_SPACE: ", ",
  SLASH: "/",
  SMOOTH: "smooth",
  HIDDEN: "hidden",
  AUTO: "auto",
  CLOSE_SIGN: "×",
  D_LETTER: "D",
  NEW_LINE: "\n",
  DOLLAR: "$",
} as const;

export type String = (typeof STRING)[keyof typeof STRING];
