export const FIRESTORE = {
  COLLECTIONS: {
    USERS: "users",
    ADMINS: "admins",
    CLIENT_CODES: "client_codes",
    HEADQUARTERS: "headquarters",
    PLANS_CONTRACT: "plans_contract",
    DOCTORS: "doctors",
    REGISTER_CODES: "register_codes",
    DOCTORS_SPECIALTIES: "doctors_specialties",
    PATIENTS: "patients",
    PATIENTS_LOG: "patients_log",
    BUFOST_SERVICES: "bufost_services",
    BUFOST_PLANS: "bufost_plans",
    CLIENT_ADMINS: "client_admins",
    DOCTORS_REGISTER_CODES: "doctors_register_codes",
    DOCTORS_USERS: "doctors_users",
    INVITES: "invites",
    MEDICATIONS: "medications",
  },
  FIELDS: {
    USER: "user",
    UID_USER: "uidUser",
    CLIENT_CODE: "client_code",
    EXPIRATION_DATE: "expiration_date",
    CLIENT_UID: "client_uid",
    NAME: "name",
    LASTNAME: "lastname",
    PHONE: "phone",
    SPECIALTIES: "specialties",
    STATE: "state",
    NATIONALITY: "nationality",
    BIRTHDATE: "birthdate",
    ADDRESS: "address",
    REGISTRATION_DATE: "registration_date",
    EMAIL: "email",
    OLD_PASSWORD: "old_password",
    AILMENTS: "ailments",
    ALLERGIES: "allergies",
    MEDICATIONS: "medications",
    DOCTORS: "doctors",
    DESCRIPTION: "description",
    FREQUENCY_USE: "frequency_use",
    DAYS: "days",
    HOURS: "hours",
    PATIENT: "patient",
    OLD_DOCTORS: "old_doctors",
    NEW_DOCTORS: "new_doctors",
    REASON: "reason",
    SHORT_DESCRIPTION: "short_description",
    LONG_DESCRIPTION: "long_description",
    ICON: "icon",
    FAILED_LOGIN_ATTEMPTS: "failed_login_attempts",
    LOGIN_COOLDOWN_EXPIRES_AT: "login_cooldown_expires_at",
    PRICE_ANNUAL: "price_annual",
    PRICE_MONTHLY: "price_monthly",
    INCLUDES: "includes",
    DISCOUNT: "discount",
    ROLE: "role",
    DOCTOR_REFERENCE: "doctor_reference",
    PLAN_ID: "plan_id",
    PHOTO: "photo",
    PHOTO_URL: "photoUrl",
    COMPLETED: "completed",
    CREATED_AT: "created_at",
    USER_REFERENCE: "user_reference",
    USER_COLLECTION: "user_collection",
    AUTH_ID: "authId",
    TOKEN: "token",
  },
  OPERATORS: {
    DOUBLE_EQUALS: "==",
    GREATER_OR_EQUAL: ">=",
    LESS_OR_EQUAL: "<=",
    LESS_THAN: "<",
    IN: "in",
  },
  SCHEDULE: {
    TIME_ZONE_COSTA_RICA: "America/Costa_Rica",
    LAST_DAY_OF_THE_MONT: "0 23 L * *",
    RETRY_COUNT_TIMES: 1,
  },
  SNAPSHOT: {
    ONLY_ONE_RESULT: 1,
  },
  DB: "medixenter-db",
  STRING_SUFFIX: "\uf8ff",
  FUNCTIONS: {
    SCHEDULE_EXPIRE_RESERVATION:
      "scheduleExpireReservation",
  },
  STATUS: {
    PENDING: "pending",
    EXPIRED: "expired",
    CONFIRMED: "confirmed",
  },
  ORDER_BY: {
    BOOKING_DATE: "bookingDate",
  },
  DIRECTION: {
    DESC: "desc",
    ASC: "asc",
  },
} as const;
export default FIRESTORE;
