/**
 * Ligature names from Material Symbols Outlined (loaded in `app/layout.tsx`).
 * Add a key here the first time a screen needs a new glyph instead of
 * writing the ligature string inline — see `MaterialIcon`.
 */
export const MATERIAL_ICON_NAME = {
  ADD: "add",
  ADD_A_PHOTO: "add_a_photo",
  ADMIN_PANEL_SETTINGS: "admin_panel_settings",
  ANCHOR: "anchor",
  ARROW_BACK: "arrow_back",
  ARROW_FORWARD: "arrow_forward",
  ATTACH_MONEY: "attach_money",
  BLOCK: "block",
  BUILD: "build",
  CALENDAR_MONTH: "calendar_month",
  CALL_SPLIT: "call_split",
  CANCEL: "cancel",
  CATEGORY: "category",
  CHECK_CIRCLE: "check_circle",
  CHECKLIST: "checklist",
  CHEVRON_RIGHT: "chevron_right",
  CLOSE: "close",
  CONTENT_COPY: "content_copy",
  DASHBOARD: "dashboard",
  DIRECTIONS_BOAT: "directions_boat",
  EDIT: "edit",
  EDIT_CALENDAR: "edit_calendar",
  ENGINEERING: "engineering",
  ERROR: "error",
  EVENT_AVAILABLE: "event_available",
  EVENT_BUSY: "event_busy",
  FILTER_LIST: "filter_list",
  GROUP: "group",
  HANDYMAN: "handyman",
  HISTORY: "history",
  INFO: "info",
  INVENTORY_2: "inventory_2",
  KAYAKING: "kayaking",
  LOCAL_GAS_STATION: "local_gas_station",
  LOCK: "lock",
  LOCK_RESET: "lock_reset",
  LOGIN: "login",
  LOGOUT: "logout",
  MAIL: "mail",
  NOTIFICATIONS: "notifications",
  OIL_BARREL: "oil_barrel",
  PAYMENTS: "payments",
  PERSON: "person",
  PERSON_ADD: "person_add",
  PHOTO_CAMERA: "photo_camera",
  RADIO_BUTTON_UNCHECKED: "radio_button_unchecked",
  REFRESH: "refresh",
  REPORT: "report",
  REMOVE: "remove",
  SAILING: "sailing",
  SAVE: "save",
  SCHEDULE: "schedule",
  SEARCH: "search",
  SEARCH_OFF: "search_off",
  SPEED: "speed",
  SPORTS_MOTORSPORTS: "sports_motorsports",
  STOREFRONT: "storefront",
  SURFING: "surfing",
  SWAP_HORIZ: "swap_horiz",
  TODAY: "today",
  TRENDING_DOWN: "trending_down",
  UNDO: "undo",
  VERIFIED: "verified",
  VISIBILITY: "visibility",
  VISIBILITY_OFF: "visibility_off",
  WARNING: "warning",
  WATER: "water",
  WAVES: "waves",
} as const;

export type MaterialIconName =
  (typeof MATERIAL_ICON_NAME)[keyof typeof MATERIAL_ICON_NAME];
