export const ICON_ALTS = {
  MAP_PIN: "Map Pin Icon",
  MAIL: "Mail Icon",
  PHONE: "Phone Icon",
  CHEVRON_LEFT: "Chevron Left Icon",
  CHEVRON_RIGHT: "Chevron Right Icon",
  LOGOUT: "Logout Icon",
  BACK: "Back Icon",
  EDIT: "Edit Icon",
  CHEVRON_DOWN_GREEN: "Chevron Down Green Icon",
  SHOPPING_CART: "Shopping Cart Icon",
  CLOSE: "Close Icon",
  MENU: "Menu Icon",
  CART: "Cart Icon",
  G_MAPS: "Google Maps Icon",
  STICKY_NOTE: "Sticky Note Icon",
  CHEVRON_DOWN: "Chevron Down Icon",
  LOGO: "MediXenter Canopy Tour Logo",
  TICKET: "Ticket Icon",
  CIRCLE_DOWN: "Circle Down Icon",
  HEALTHCARE: "Healthcare Icon",
  MEDICAL_TABLE: "Medical Table Icon",
  ICON: "Icon",
  NURSE: "Nurse",
  MEDIXENTER_LOGO: "Medixenter Logo",
  WHATSAPP: "Whatsapp icon",
  X: "X icon",
  INSTAGRAM: "Instagram icon",
  FACEBOOK: "/Facebook icon",
  CLOSE_ICON_MODAL: "Close icon modal",
  UPLOAD_ICON: "Upload icon",
  TOAST_ICON: "Toast icon",
  CLOSE_TOAST_ICON: "Close toast icon",
  WARNING: "Warning Icon",
  PENCIL: "Pencil icon",
  DELETE: "Delete icon",
  EYE: "Eye icon",
  STATE_CIRCLE: "State Circle icon",
  ARROW_DOWN: "Arrow Down icon",
  RECOVER: "Recover icon",
  CHECK_MARK: "Check Mark Icon",
  EYE_VISIBLE: "Eye visible icon",
  EYE_HIDDEN: "Eye hidden icon",
};
