export const ICON_PATHS = {
  LOGO: "/logo/mediXenter.svg",
  SHOPPING_CART: "/icons/shopping-cart.svg",
  CHEVRON_DOWN: "/icons/chevron-down.svg",
  MENU: "/icons/menu.svg",
  CLOSE: "/icons/x.svg",
  TICKET: "/icons/ticket.svg",
  LOGOUT: "/icons/logout.svg",
  DOCTOR: "/icons/doctor.svg",
  VISITING: "/icons/house-visiting.svg",
  CIRCLE_DOWN: "/icons/circle-down.svg",
  HEALTHCARE: "/icons/healthcare.svg",
  MEDICAL_TABLE: "/icons/medical-table.svg",
  WHATSAPP_WHITE: "/icons/whatsapp_white_border.svg",
  X_WHITE: "/icons/X_white_border.svg",
  INSTAGRAM_WHITE: "/icons/insta_white_border.svg",
  FACEBOOK_WHITE: "/icons/facebook_white_border.svg",
  X_MODAL: "/icons/x-modal.svg",
  UPLOAD: "/icons/upload.svg",
  WARNING: "/icons/warning.svg",
  PENCIL:
    "/icons/edit-interface-multimedia-svgrepo-com.svg",
  DELETE: "/icons/delete-svgrepo-com.svg",
  EYE: "/icons/eye-scan-svgrepo-com.svg",
  STATE_CIRCLE: "/icons/state-circle.svg",
  ARROW_DOWN: "/icons/arrow-down.svg",
  RECOVER:
    "/icons/arrow-interface-multimedia-svgrepo-com.svg",
  CLINIC: "/icons/clinic.svg",
  CHECK_MARK: "/icons/check-mark.svg",
  EYE_VISIBLE: "/icons/eye.svg",
  EYE_HIDDEN: "/icons/eye-off.svg",
};
